# -*- coding: utf-8 -*-
"""4300 final proj test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hbIn-4ccYPKi1t-xk2hZD46q0X8a0UhO
"""

import json

def extract_keywords(json_file):
    keyword_counts = {}

    with open(json_file, 'r') as f:
        data = json.load(f)
        for molecule in data['molecules']:
            if 'flavor_profile' in molecule:
                keywords = molecule['flavor_profile'].split('@')
                for keyword in keywords:
                    if keyword: # ignore empty str
                        if keyword in keyword_counts:
                            keyword_counts[keyword] += 1
                        else:
                            keyword_counts[keyword] = 1

    return dict(sorted(keyword_counts.items(), key=lambda item: item[1], reverse=True))

keyword_counts = extract_keywords('46.json')
for keyword, count in keyword_counts.items():
    print(f"{keyword}: {count}")

import os

def extract_multi(json_files):
    all_keyword_counts = {}

    for json_file in json_files:
        keyword_counts = extract_keywords(json_file)
        all_keyword_counts[os.path.basename(json_file)] = keyword_counts

    return all_keyword_counts

all_keyword_counts = extract_multi(['46.json', '60.json', '88.json'])

for file, keyword_counts in all_keyword_counts.items():
    print(f"\n{file}:")
    for keyword, count in keyword_counts.items():
        print(f"{keyword}: {count}")

from collections import Counter

def merge_counts(json_files):
    merged_keyword_counts = Counter()

    for json_file in json_files:
        keyword_counts = extract_keywords(json_file)
        merged_keyword_counts.update(keyword_counts)

    merged_keyword_counts = dict(sorted(merged_keyword_counts.items(), key=lambda item: item[1], reverse=True))
    return merged_keyword_counts

merged_keyword_counts = merge_counts(['46.json', '60.json', '88.json'])
for keyword, count in merged_keyword_counts.items():
    print(f"{keyword}: {count}")

